2021-02-05 16:44:14,848 INFO    MainThread:9387 [wandb_setup.py:_flush():70] setting env: {}
2021-02-05 16:44:14,849 INFO    MainThread:9387 [wandb_setup.py:_flush():70] multiprocessing start_methods=fork,spawn,forkserver
2021-02-05 16:44:14,849 INFO    MainThread:9387 [wandb_setup.py:_flush():70] setting login settings: {'api_key': '6d802b44b97d25931bacec09c5f1095e6c28fe36'}
2021-02-05 16:44:14,849 INFO    MainThread:9387 [wandb_setup.py:_flush():70] setting login settings: {'api_key': '6d802b44b97d25931bacec09c5f1095e6c28fe36'}
2021-02-05 16:44:14,849 INFO    MainThread:9387 [wandb_setup.py:_flush():70] setting login settings: {}
2021-02-05 16:44:14,849 INFO    MainThread:9387 [wandb_init.py:_log_setup():318] Logging user logs to /home/wolf/MyCode/HPC/wandb/run-20210205_164414-32vpvt14/logs/debug.log
2021-02-05 16:44:14,849 INFO    MainThread:9387 [wandb_init.py:_log_setup():319] Logging internal logs to /home/wolf/MyCode/HPC/wandb/run-20210205_164414-32vpvt14/logs/debug-internal.log
2021-02-05 16:44:17,878 INFO    MainThread:9387 [wandb_run.py:_console_start():1399] atexit reg
2021-02-05 16:44:17,879 INFO    MainThread:9387 [wandb_run.py:_redirect():1262] redirect: SettingsConsole.REDIRECT
2021-02-05 16:44:17,880 INFO    MainThread:9387 [wandb_run.py:_redirect():1267] Redirecting console.
2021-02-05 16:44:17,880 INFO    MainThread:9387 [redirect.py:install():213] install start
2021-02-05 16:44:17,885 INFO    MainThread:9387 [redirect.py:install():228] install stop
2021-02-05 16:44:17,885 INFO    MainThread:9387 [redirect.py:install():213] install start
2021-02-05 16:44:17,889 INFO    MainThread:9387 [redirect.py:install():228] install stop
2021-02-05 16:44:17,889 INFO    MainThread:9387 [wandb_run.py:_redirect():1313] Redirects installed.
2021-02-05 16:44:28,157 INFO    MainThread:9387 [wandb_run.py:_atexit_cleanup():1369] got exitcode: 1
2021-02-05 16:44:28,157 INFO    MainThread:9387 [wandb_run.py:_restore():1341] restore
2021-02-05 16:44:28,158 INFO    MainThread:9387 [redirect.py:uninstall():232] uninstall start
2021-02-05 16:44:28,158 INFO    MainThread:9387 [redirect.py:_stop():287] _stop: stdout
2021-02-05 16:44:28,158 INFO    MainThread:9387 [redirect.py:_stop():293] _stop closed: stdout
2021-02-05 16:44:28,158 INFO    stdout    :9387 [redirect.py:_pipe_relay():129] relay done saw last write: stdout
2021-02-05 16:44:28,159 INFO    stdout    :9387 [redirect.py:_pipe_relay():145] relay done done: stdout
2021-02-05 16:44:28,159 INFO    MainThread:9387 [redirect.py:_stop():299] _stop joined: stdout
2021-02-05 16:44:28,159 INFO    MainThread:9387 [redirect.py:_stop():301] _stop rd closed: stdout
2021-02-05 16:44:28,159 INFO    MainThread:9387 [redirect.py:uninstall():236] uninstall done
2021-02-05 16:44:28,159 INFO    MainThread:9387 [redirect.py:uninstall():232] uninstall start
2021-02-05 16:44:28,159 INFO    MainThread:9387 [redirect.py:_stop():287] _stop: stderr
2021-02-05 16:44:28,159 INFO    MainThread:9387 [redirect.py:_stop():293] _stop closed: stderr
2021-02-05 16:44:28,160 INFO    stderr    :9387 [redirect.py:_pipe_relay():129] relay done saw last write: stderr
2021-02-05 16:44:28,161 INFO    stderr    :9387 [redirect.py:_pipe_relay():145] relay done done: stderr
2021-02-05 16:44:28,161 INFO    MainThread:9387 [redirect.py:_stop():299] _stop joined: stderr
2021-02-05 16:44:28,161 INFO    MainThread:9387 [redirect.py:_stop():301] _stop rd closed: stderr
2021-02-05 16:44:28,162 INFO    MainThread:9387 [redirect.py:uninstall():236] uninstall done
2021-02-05 16:44:28,438 INFO    MainThread:9387 [wandb_run.py:_wait_for_finish():1492] got exit ret: file_counts {
  wandb_count: 2
  other_count: 1
}
pusher_stats {
  uploaded_bytes: 6234
  total_bytes: 6234
}

2021-02-05 16:44:30,443 INFO    MainThread:9387 [wandb_run.py:_wait_for_finish():1492] got exit ret: done: true
exit_result {
}
file_counts {
  wandb_count: 6
  other_count: 1
}
pusher_stats {
  uploaded_bytes: 13827
  total_bytes: 13827
}

2021-02-05 16:44:31,917 INFO    MainThread:9387 [wandb_run.py:_show_files():1714] logging synced files
2021-02-05 16:44:31,920 INFO    MainThread:9387 [internal.py:handle_exit():156] Internal process exited
