2021-02-05 16:42:16,433 INFO    MainThread:9127 [wandb_setup.py:_flush():70] setting env: {}
2021-02-05 16:42:16,433 INFO    MainThread:9127 [wandb_setup.py:_flush():70] multiprocessing start_methods=fork,spawn,forkserver
2021-02-05 16:42:16,433 INFO    MainThread:9127 [wandb_setup.py:_flush():70] setting login settings: {'api_key': '6d802b44b97d25931bacec09c5f1095e6c28fe36'}
2021-02-05 16:42:16,433 INFO    MainThread:9127 [wandb_setup.py:_flush():70] setting login settings: {'api_key': '6d802b44b97d25931bacec09c5f1095e6c28fe36'}
2021-02-05 16:42:16,433 INFO    MainThread:9127 [wandb_setup.py:_flush():70] setting login settings: {}
2021-02-05 16:42:16,433 INFO    MainThread:9127 [wandb_init.py:_log_setup():318] Logging user logs to /home/wolf/MyCode/HPC/wandb/run-20210205_164216-ol5zti1c/logs/debug.log
2021-02-05 16:42:16,434 INFO    MainThread:9127 [wandb_init.py:_log_setup():319] Logging internal logs to /home/wolf/MyCode/HPC/wandb/run-20210205_164216-ol5zti1c/logs/debug-internal.log
2021-02-05 16:42:20,021 INFO    MainThread:9127 [wandb_run.py:_console_start():1399] atexit reg
2021-02-05 16:42:20,021 INFO    MainThread:9127 [wandb_run.py:_redirect():1262] redirect: SettingsConsole.REDIRECT
2021-02-05 16:42:20,022 INFO    MainThread:9127 [wandb_run.py:_redirect():1267] Redirecting console.
2021-02-05 16:42:20,022 INFO    MainThread:9127 [redirect.py:install():213] install start
2021-02-05 16:42:20,033 INFO    MainThread:9127 [redirect.py:install():228] install stop
2021-02-05 16:42:20,033 INFO    MainThread:9127 [redirect.py:install():213] install start
2021-02-05 16:42:20,036 INFO    MainThread:9127 [redirect.py:install():228] install stop
2021-02-05 16:42:20,036 INFO    MainThread:9127 [wandb_run.py:_redirect():1313] Redirects installed.
2021-02-05 16:42:30,095 INFO    MainThread:9127 [wandb_run.py:_atexit_cleanup():1369] got exitcode: 1
2021-02-05 16:42:30,096 INFO    MainThread:9127 [wandb_run.py:_restore():1341] restore
2021-02-05 16:42:30,096 INFO    MainThread:9127 [redirect.py:uninstall():232] uninstall start
2021-02-05 16:42:30,097 INFO    MainThread:9127 [redirect.py:_stop():287] _stop: stdout
2021-02-05 16:42:30,097 INFO    stdout    :9127 [redirect.py:_pipe_relay():129] relay done saw last write: stdout
2021-02-05 16:42:30,097 INFO    stdout    :9127 [redirect.py:_pipe_relay():145] relay done done: stdout
2021-02-05 16:42:30,097 INFO    MainThread:9127 [redirect.py:_stop():293] _stop closed: stdout
2021-02-05 16:42:30,098 INFO    MainThread:9127 [redirect.py:_stop():299] _stop joined: stdout
2021-02-05 16:42:30,098 INFO    MainThread:9127 [redirect.py:_stop():301] _stop rd closed: stdout
2021-02-05 16:42:30,098 INFO    MainThread:9127 [redirect.py:uninstall():236] uninstall done
2021-02-05 16:42:30,098 INFO    MainThread:9127 [redirect.py:uninstall():232] uninstall start
2021-02-05 16:42:30,098 INFO    MainThread:9127 [redirect.py:_stop():287] _stop: stderr
2021-02-05 16:42:30,098 INFO    MainThread:9127 [redirect.py:_stop():293] _stop closed: stderr
2021-02-05 16:42:30,106 INFO    stderr    :9127 [redirect.py:_pipe_relay():129] relay done saw last write: stderr
2021-02-05 16:42:30,106 INFO    stderr    :9127 [redirect.py:_pipe_relay():145] relay done done: stderr
2021-02-05 16:42:30,106 INFO    MainThread:9127 [redirect.py:_stop():299] _stop joined: stderr
2021-02-05 16:42:30,106 INFO    MainThread:9127 [redirect.py:_stop():301] _stop rd closed: stderr
2021-02-05 16:42:30,106 INFO    MainThread:9127 [redirect.py:uninstall():236] uninstall done
2021-02-05 16:42:30,300 INFO    MainThread:9127 [wandb_run.py:_wait_for_finish():1492] got exit ret: file_counts {
  wandb_count: 2
  other_count: 1
}
pusher_stats {
  uploaded_bytes: 6232
  total_bytes: 6232
}

2021-02-05 16:42:32,304 INFO    MainThread:9127 [wandb_run.py:_wait_for_finish():1492] got exit ret: done: true
exit_result {
}
file_counts {
  wandb_count: 6
  other_count: 1
}
pusher_stats {
  uploaded_bytes: 10259
  total_bytes: 10259
}

2021-02-05 16:42:33,994 INFO    MainThread:9127 [wandb_run.py:_show_files():1714] logging synced files
2021-02-05 16:42:33,998 INFO    MainThread:9127 [internal.py:handle_exit():156] Internal process exited
