x_train shape: (50000, 32, 32, 3)
50000 train samples
10000 test samples
2021-02-05 16:37:18.429581: I tensorflow/compiler/jit/xla_cpu_device.cc:41] Not creating XLA devices, tf_xla_enable_xla_devices not set
2021-02-05 16:37:18.431395: W tensorflow/stream_executor/platform/default/dso_loader.cc:60] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory
2021-02-05 16:37:18.431413: W tensorflow/stream_executor/cuda/cuda_driver.cc:326] failed call to cuInit: UNKNOWN ERROR (303)
2021-02-05 16:37:18.431439: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (I-Wolf): /proc/driver/nvidia/version does not exist
2021-02-05 16:37:18.431755: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2021-02-05 16:37:18.431983: I tensorflow/compiler/jit/xla_gpu_device.cc:99] Not creating XLA devices, tf_xla_enable_xla_devices not set
Traceback (most recent call last):
  File "/home/wolf/MyCode/HPC/ml_assignment/cifar10_hvd_2.py", line 72, in <module>
    model.add(Dense(num_classes, activation='sofmax'))
  File "/home/wolf/miniconda3/envs/wolf/lib/python3.8/site-packages/tensorflow/python/keras/layers/core.py", line 1161, in __init__
    self.activation = activations.get(activation)
  File "/home/wolf/miniconda3/envs/wolf/lib/python3.8/site-packages/tensorflow/python/util/dispatch.py", line 201, in wrapper
    return target(*args, **kwargs)
  File "/home/wolf/miniconda3/envs/wolf/lib/python3.8/site-packages/tensorflow/python/keras/activations.py", line 573, in get
    return deserialize(identifier)
  File "/home/wolf/miniconda3/envs/wolf/lib/python3.8/site-packages/tensorflow/python/util/dispatch.py", line 201, in wrapper
    return target(*args, **kwargs)
  File "/home/wolf/miniconda3/envs/wolf/lib/python3.8/site-packages/tensorflow/python/keras/activations.py", line 532, in deserialize
    return deserialize_keras_object(
  File "/home/wolf/miniconda3/envs/wolf/lib/python3.8/site-packages/tensorflow/python/keras/utils/generic_utils.py", line 377, in deserialize_keras_object
    raise ValueError(
ValueError: Unknown activation function: sofmax
